routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();

Route::get('/', 'HomeController@index');
Route::get('entries/user/{id}', 'EntryUserController@show');

Route::middleware(['auth'])->group(function () {
    Route::resource('entries', 'EntryController', ['except' => ['destroy', 'show', 'index']]);
    Route::get('tweet/hide/{idTweet}', 'TweetController@hideTweet');
    Route::get('tweet/delete/{idTweet}', 'TweetController@deleteTweet');
});

app/Entry.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Entry extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'title', 'content', 'author', 'created_at'
    ];

    /**
     * Get the user that owns the entry.
     */
    public function user()
    {
        return $this->belongsTo('App\User', 'author', 'id');
    }
}

app/Tweet.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Database\Eloquent\Model;

class Tweet extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'is_hidden', 'author', 'id_tweet'
    ];

    /**
     * Get the user that owns the tweet.
     */
    public function post()
    {
        return $this->belongsTo('App\User', 'author', 'id');
    }
}

app/User.php
<?php

namespace App;

use App\Entry;
use App\Tweet;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password', 'twitter_username'
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * Get the entries for the user.
     */
    public function entries()
    {
        return $this->hasMany(Entry::class, 'author');
    }

    /**
     * Get the tweets for the user.
     */
    public function tweets()
    {
        return $this->hasMany(Tweet::class);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/EntryController.php
<?php

namespace App\Http\Controllers;

use App\Entry;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class EntryController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('entries.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
            'title' => 'required|max:150',
            'content' => 'required|max:255',
        ]);

        $data = $request->only(['title', 'content']);
        $data['author'] = Auth::user()->id;

        Entry::create($data);

        return redirect()->to('/')
            ->with('success', 'Entry created successfully.');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Entry $entry)
    {
        return view('entries.edit', compact('entry'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, Entry $entry)
    {
        $request->validate([
            'title' => 'required|max:150',
            'content' => 'required|max:255',
        ]);

        $data = $request->only(['title', 'content']);
        $data['author'] = Auth::user()->id;

        $entry->update($data);

        return redirect()->to('/')
            ->with('success', 'Entry updated successfully');
    }
}

app/Http/Controllers/EntryUserController.php
<?php

namespace App\Http\Controllers;

use App\User;
use App\Tweet;
use Illuminate\Http\Request;
use GuzzleHttp\Client;
use GuzzleHttp\Exception\RequestException;

class EntryUserController extends Controller
{
    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        $user = User::whereId($id)->with('entries')->first();
        $hiddenTweets = Tweet::where('author', $id)->where('is_hidden', 1)->get()->toArray();

        $client = new Client([
            'headers' => [
                'Authorization' => 'Bearer AAAAAAAAAAAAAAAAAAAAAPNRCAEAAAAAU8rTyhD%2FkQ3S0yWr1dTvnXC5yhY%3DmPLGYNBGmGo9QgqOIqfid8viNj1zfbcPj9j7D3ZEe4nTImmxvG'
            ]
        ]);

        $tweets = [];
        try {
            $promise = $client->getAsync('https://api.twitter.com/1.1/statuses/user_timeline.json', [
                'query' => [
                    'screen_name' => $user->twitter_username
                ]
            ])->then(
                function ($response) {
                    return  $response->getStatusCode() == 200 ? json_decode($response->getBody(), true) : [];
                },
                function ($exception) {
                    return [];
                }
            );
            $tweets = $promise->wait();
        } catch (RequestException $e) {
            $tweets = [];
        }

        foreach ($tweets as $key => $tweet) {
            $findTweet = array_search($tweet['id'], array_column($hiddenTweets, 'id_tweet'));
            $tweets[$key]['is_hidden'] = gettype($findTweet) == "boolean" ? false : true;
        }

        return view('entries.user.profile', ['user' => $user, 'tweets' => $tweets]);
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use App\Entry;
use Illuminate\Http\Request;
use Illuminate\Pagination\LengthAwarePaginator as Paginator;

class HomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function index(Request $request)
    {
        $page = $request->has('page') ? $request->input('page') : 1;
        $limitOfRegister = 3;

        $getAllEntries = Entry::with('user')
            ->orderBy('created_at', 'desc')
            ->get()
            ->groupBy('author')
            ->toArray();

        $offset = $page == 1 ? 0 : (($page * 3) - 3);
        $sliceEntries = array_slice($getAllEntries, $offset, $limitOfRegister);

        $entries = new Paginator($sliceEntries, count($getAllEntries), $limitOfRegister, $page,  [
            'path'  => $request->url(),
            'query' => $request->query(),
        ]);

        return view('entries.list', ['entries' => $entries]);
    }
}

app/Http/Controllers/TweetController.php
<?php

namespace App\Http\Controllers;

use App\Tweet;
use Illuminate\Http\Request;
use Illuminate\Support\Facades\Auth;

class TweetController extends Controller
{
    public function hideTweet($idTweet)
    {
        $data['author'] = Auth::user()->id;
        $data['is_hidden'] = 1;
        $data['id_tweet'] = $idTweet;

        Tweet::create($data);

        return response()->json([
            'status' => 200,
            'message' => 'Successfully hidden tweet!'
        ]);
    }

    public function deleteTweet($idTweet)
    {
        $tweet = Tweet::where('id_tweet', $idTweet)->first();
        $tweet->delete();

        return response()->json([
            'status' => 200,
            'message' => 'Successfully show tweet!'
        ]);
    }
}

resources/views/entries/create.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Create Entry</div>

                <div class="card-body">
                    <form action="{{ route('entries.store') }}" method="POST">
                        @csrf

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" required autocomplete="title" autofocus>

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="content" class="col-md-4 col-form-label text-md-right">{{ __('content') }}</label>

                            <div class="col-md-6">
                                <input id="content" type="text" class="form-control @error('content') is-invalid @enderror" name="content" required autocomplete="content" autofocus>

                                @error('content')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Create Entry') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/entries/edit.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Edit Entry</div>

                <div class="card-body">
                    <form action="{{ route('entries.update',$entry->id) }}" method="POST">
                        @csrf
                        @method('PUT')

                        <div class="form-group row">
                            <label for="title" class="col-md-4 col-form-label text-md-right">{{ __('title') }}</label>

                            <div class="col-md-6">
                                <input id="title" type="text" class="form-control @error('title') is-invalid @enderror" name="title" value="{{ $entry->title }}" required autocomplete="title" autofocus>

                                @error('title')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="content" class="col-md-4 col-form-label text-md-right">{{ __('content') }}</label>

                            <div class="col-md-6">
                                <input id="content" type="text" class="form-control @error('content') is-invalid @enderror" name="content" value="{{ $entry->content }}" required autocomplete="content" autofocus>

                                @error('content')
                                <span class="invalid-feedback" role="alert">
                                    <strong>{{ $message }}</strong>
                                </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Update Entry') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/entries/list.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row justify-content-center">
        <div class="col-md-8">
            @foreach ($entries as $entry)
            @foreach ($entry as $key => $userEntry)
            @if ($key <= 2) <div class="card list-entries-card">
                <div class="card-body">
                    <h2 class="card-title list-entries-title">{{$userEntry['title']}}</h2>
                    <h6 class="card-subtitle mb-2 text-muted">Author
                        <a href="{{'entries/user/'.$userEntry['user']['id']}}">{{$userEntry['user']['username']}}</a>
                    </h6>
                    <p class="card-text">{{$userEntry['content']}}</p>
                    @auth
                    @if(Auth::user()->id == $userEntry['user']['id'])
                    <hr class="separator">
                    <a href="{{url('/entries/'.$userEntry['id'].'/edit')}}" class="btn-filled">Edit Entry</a>
                    @endif
                    @endauth
                </div>
        </div>
        @endif @endforeach @endforeach
        {{ $entries->links() }}
    </div>
</div>
</div> @endsection

resources/views/entries/user/profile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="alert alert-success" style="display:none" role="alert" id="alert"></div>
    <div class="row justify-content-center">
        <div class="col-md-4">
            @foreach ($tweets as $tweet)
            @if($tweet['is_hidden'])
            @auth
            @if(Auth::user()->id == $user['id'])
            <div class="card list-tweets-card">
                <div class="card-body">
                    <h5 class="card-title">{{$user->twitter_username}}</h5>
                    <p class="card-text">{{$tweet['text']}}</p>
                    <hr class="separator">
                    <a href="#" class="showTweet btn-showTweet" name='{{$tweet["id"]}}|show'>Show Tweet ?</a>
                </div>
            </div>
            @endif
            @endauth
            @else
            <div class="card list-tweets-card">
                <div class='card-body'>
                    <h5 class="card-title">{{$user->twitter_username}}</h5>
                    <p class="card-text">{{$tweet['text']}}</p>
                    @auth
                    @if(Auth::user()->id == $user['id'])
                    <hr class="separator">
                    <a href="#" class="hideTweet btn-hideTweet" name='{{$tweet["id"]}}|hide'>Hide Tweet ?</a>
                    @endif
                    @endauth
                </div>
            </div>
            @endif
            @endforeach
        </div>
        <div class="col-md-8">
            @foreach ($user->entries as $entry)
            <div class="card list-entries-card">
                <div class="card-body">
                    <h2 class="card-title list-entries-title">{{$entry->title}}</h2>
                    <p class="card-text">{{$entry->content}}</p>
                    @auth
                    @if(Auth::user()->id == $user['id'])
                    <hr class="separator">
                    <a href="{{url('/entries/'.$entry->id.'/edit')}}" class="btn-filled">Edit Entry</a>
                    @endif
                    @endauth
                </div>
            </div>
            @endforeach
        </div>
    </div>
</div>

<div class="modal fade" id="confirmHideOrShowTweet" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="modalTitle"></h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>
            <div class="modal-body">
                <H3 id="modalQuestion"></H3>
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-primary" data-dismiss="modal">CANCEL</button>
                <button type="button" class="btn btn-danger" id="buttonConfirmationAction"></button>
                <button type="button" class="btn btn-danger" id="loadingButton">
                    <span class="spinner-border spinner-border-sm" role="status" aria-hidden="true"></span>
                    Loading...
                </button>
            </div>
        </div>
    </div>
</div>
@endsection

@section('script')
<script>
    jQuery(document).ready(() => {
        // -----------------  Declaration Methods 
        const eventHideTweet = () => {
            $('.hideTweet').click(event => {
                // Get Tweet's id 
                idTweet = getIdTweet(event);
                // Set modal title
                $('#modalTitle').text('HIDE TWEET');
                // Set modal question
                $('#modalQuestion').html('Are you sure you want to <span>HIDE</span> Tweet?');
                // Set text to button 
                $('#buttonConfirmationAction').text('YES, HIDE TWEET');
                // Open modal to confirm action
                $('#confirmHideOrShowTweet').modal('show');
                // Set action
                action = "hide";
            })
        }

        const eventShowTweet = () => {
            $('.showTweet').click(event => {
                // Get Tweet's id 
                idTweet = getIdTweet(event);
                // Set modal title
                $('#modalTitle').text('SHOW TWEET')
                // Set modal question
                $('#modalQuestion').html('Are you sure you want to <span>SHOW</span> Tweet?')
                // Set text to button 
                $('#buttonConfirmationAction').text('YES, SHOW TWEET')
                // Open modal to confirm action
                $('#confirmHideOrShowTweet').modal('show');
                // Set action
                action = "show";
            })
        }

        const getIdTweet = (event) => {
            const nameTweet = $(event.target).attr('name');
            const splitNameTweet = nameTweet.split('|');
            return splitNameTweet[0];
        }

        const hideTweet = (url_global, idTweet) => {
            return $.ajax({
                url: `${url_global}/tweet/hide/${idTweet}`,
                dataType: 'json',
                method: 'get'
            })
        }

        const showTwee = (url_global, idTweet) => {
            return $.ajax({
                url: `${url_global}/tweet/delete/${idTweet}`,
                dataType: 'json',
                method: 'get'
            })
        }

        const showAlertMessage = (message) => {
            $('#alert').show();
            $('#alert').text(message);
            setTimeout(() => {
                $('#alert').hide();
            }, 5000)
        }

        const hideModal = () => {
            $('#confirmHideOrShowTweet').modal('hide');
        }

        // ----------------- End methods

        $('#loadingButton').hide();
        $('#alert').hide()
        const url_global = '{{url("/")}}';
        let idTweet;
        let action;

        // Listen to link hideTweet
        eventHideTweet();

        // Listen to link showTweet
        eventShowTweet();

        $('#buttonConfirmationAction').click((event) => {
            // Hide button confirmation 
            $('#buttonConfirmationAction').hide()
            // Show button loading
            $('#loadingButton').show();

            if (action === 'hide') {
                hideTweet(url_global, idTweet)
                    .done((response) => {
                        // Show alert with message
                        showAlertMessage(response.message);
                        // Close Modal
                        hideModal()
                        $(`a[name ="${idTweet}|hide"]`).parent().append(`<a href="#" class="showTweet btn-showTweet" name='${idTweet}|show'>Show Tweet ?</a`);
                        $(`a[name ="${idTweet}|hide"]`).hide();
                        // Listen event showTweet
                        eventShowTweet();
                    }).always(() => {
                        $('#buttonConfirmationAction').show()
                        $('#loadingButton').hide();
                    })
            } else {
                showTwee(url_global, idTweet)
                    .done((response) => {
                        // Show alert with message
                        showAlertMessage(response.message)
                        // Close Modal
                        hideModal()
                        $(`a[name ="${idTweet}|show"]`).parent().append(`   <a href="#" class="hideTweet btn-hideTweet" name='${idTweet}|hide'>Hide Tweet ?</a>`);
                        $(`a[name ="${idTweet}|show"]`).hide();
                        // Listen event hideTweet
                        eventHideTweet();
                    }).always(() => {
                        $('#buttonConfirmationAction').show()
                        $('#loadingButton').hide();
                    })
            }
        })
    })
</script>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Javascript: jQuery, Popper and Bootstrap -->
    <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link href="{{ asset('css/_card_entries.css') }}" rel="stylesheet">
</head>

<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">Entries</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                        </li>
                        @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                        @endif
                        @else
                        <li class="nav-item">
                            <a class="nav-link btn-filled" style="color:white !important" href="{{ route('entries.create') }}">Create Entry</a>
                        </li>
                        <li class=" nav-item dropdown">
                            <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                {{ Auth::user()->username }} <span class="caret"></span>
                            </a>

                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{{ route('logout') }}" onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                    {{ __('Logout') }}
                                </a>

                                <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                    @csrf
                                </form>
                            </div>
                        </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
    @yield('script')
</body>

</html>